//! What a search may read, and what it says it left out.
//!
//! Two passes, because one of them is free. A name and a size rule out most of a repository
//! before anything is opened; only what survives is read, and the rest — a binary, a minified
//! bundle, a generated file — is ruled out on what is inside it.

/// A file bigger than this is not source somebody wrote.
pub const MOST_BYTES: u64 = 512 * 1024;

/// A line longer than this in a file of few lines is a bundle, not code.
const LONG_LINE: usize = 500;

/// How far into a file a generated-by marker is still a header.
const HEADER: usize = 40;

/// Why a file was left out, in the words the result reports.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Left {
    Big,
    Binary,
    Credential,
    Generated,
    Locked,
    Minified,
}

impl Left {
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Big => "too big",
            Self::Binary => "not text",
            Self::Credential => "may hold credentials",
            Self::Generated => "generated",
            Self::Locked => "a lock file",
            Self::Minified => "minified",
        }
    }
}

/// Extensions that are never source: pictures, archives, objects, fonts, media.
const OPAQUE: &[&str] = &[
    "png", "jpg", "jpeg", "gif", "bmp", "ico", "webp", "tiff", "svgz", "pdf", "zip", "gz", "bz2",
    "xz", "zst", "tar", "7z", "rar", "jar", "war", "so", "dylib", "dll", "exe", "o", "a", "rlib",
    "rmeta", "class", "pyc", "pyo", "wasm", "bin", "dat", "db", "sqlite", "woff", "woff2", "ttf",
    "otf", "eot", "mp3", "mp4", "wav", "ogg", "webm", "mov", "avi", "mkv", "flac", "psd", "ai",
    "sketch", "ipa", "apk", "dmg", "iso", "img", "pack", "idx",
];

/// Names and endings that hold secrets. A repository should not have them; a search that read one
/// anyway would put it in a model's context, which is the one place it can never be taken back
/// from. The rule is on the name because there is no reading a file to find out safely.
const SECRET: &[&str] = &[
    ".env",
    ".pem",
    ".key",
    ".p12",
    ".pfx",
    ".jks",
    ".keystore",
    ".ppk",
    ".netrc",
    ".npmrc",
    ".pypirc",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "credentials",
    "secrets",
    "secret",
];

/// Endings that are a resolver's output rather than anybody's writing.
const LOCKED: &[&str] = &[
    ".lock",
    "-lock.json",
    "package-lock.json",
    "go.sum",
    "npm-shrinkwrap.json",
];

/// Endings that are a build's output.
const BUILT: &[&str] = &[".min.js", ".min.css", ".map", ".bundle.js", ".chunk.js"];

/// Whether `path` at `bytes` may be opened at all, or why not.
#[must_use]
pub fn by_name(path: &str, bytes: u64) -> Option<Left> {
    let name = path.rsplit('/').next().unwrap_or(path).to_lowercase();
    if SECRET
        .iter()
        .any(|mark| name == *mark || name.starts_with(mark) || name.ends_with(mark))
    {
        return Some(Left::Credential);
    }
    if LOCKED.iter().any(|mark| name.ends_with(mark)) {
        return Some(Left::Locked);
    }
    if BUILT.iter().any(|mark| name.ends_with(mark)) {
        return Some(Left::Minified);
    }
    if let Some(extension) = name.rsplit_once('.').map(|(_, tail)| tail)
        && OPAQUE.contains(&extension)
    {
        return Some(Left::Binary);
    }
    (bytes > MOST_BYTES).then_some(Left::Big)
}

/// Whether what was read is worth searching, or why not.
#[must_use]
pub fn by_content(text: &str) -> Option<Left> {
    if text.contains('\0') {
        return Some(Left::Binary);
    }
    let lines: Vec<&str> = text.lines().collect();
    if lines
        .iter()
        .take(HEADER)
        .any(|line| generated(&line.to_lowercase()))
    {
        return Some(Left::Generated);
    }
    let long = lines.iter().filter(|line| line.len() > LONG_LINE).count();
    (long > 0 && long * 4 >= lines.len()).then_some(Left::Minified)
}

/// The markers a generator leaves behind, all of which are conventions rather than guesses.
fn generated(line: &str) -> bool {
    line.contains("@generated")
        || line.contains("do not edit")
        || line.contains("code generated by")
        || line.contains("automatically generated")
        || line.contains("autogenerated")
}
