use super::*;

fn fragment(path: &str, from: usize, to: usize, text: &str) -> Fragment {
    Fragment {
        path: path.to_owned(),
        from,
        to,
        text: text.to_owned(),
    }
}

#[test]
fn a_file_that_may_hold_a_key_is_never_opened() {
    for name in [
        ".env",
        ".env.production",
        "id_rsa",
        "server.pem",
        "aws/credentials",
        "secrets.yml",
    ] {
        assert_eq!(
            eligible::by_name(name, 100),
            Some(Left::Credential),
            "{name} would have gone into a model's context"
        );
    }
}

#[test]
fn what_nobody_wrote_is_left_out() {
    assert_eq!(eligible::by_name("Cargo.lock", 10), Some(Left::Locked));
    assert_eq!(
        eligible::by_name("package-lock.json", 10),
        Some(Left::Locked)
    );
    assert_eq!(eligible::by_name("app.min.js", 10), Some(Left::Minified));
    assert_eq!(eligible::by_name("logo.png", 10), Some(Left::Binary));
    assert_eq!(
        eligible::by_name("big.rs", eligible::MOST_BYTES + 1),
        Some(Left::Big)
    );
    assert_eq!(eligible::by_name("src/main.rs", 4_000), None);
}

#[test]
fn a_generated_file_is_recognised_by_what_it_says_about_itself() {
    assert_eq!(
        eligible::by_content("// Code generated by protoc. DO NOT EDIT.\nfn a() {}"),
        Some(Left::Generated)
    );
    assert_eq!(eligible::by_content("fn a() {}\n"), None);
    assert_eq!(
        eligible::by_content(&format!("{}\n", "x".repeat(900))),
        Some(Left::Minified)
    );
    assert_eq!(eligible::by_content("a\0b"), Some(Left::Binary));
}

#[test]
fn a_marker_deep_in_a_file_is_not_a_header() {
    let body = format!("{}// @generated\n", "fn a() {}\n".repeat(80));
    assert_eq!(
        eligible::by_content(&body),
        None,
        "a file mentioning the marker is not a generated file"
    );
}

#[test]
fn a_passage_is_cut_at_a_blank_line_and_knows_where_it_came_from() {
    let mut text = String::new();
    for nth in 1..=30 {
        text.push_str(&format!("line {nth}\n"));
    }
    text.push('\n');
    for nth in 32..=60 {
        text.push_str(&format!("line {nth}\n"));
    }
    let cut = fragment::cut("a.rs", &text);
    assert!(cut.len() >= 2, "{cut:?}");
    assert_eq!(cut[0].from, 1);
    assert_eq!(cut[0].to, 31, "the blank line goes with the passage above");
    assert_eq!(cut[1].from, 32);
    assert_eq!(cut[0].at(), "a.rs:1-31");
}

#[test]
fn every_line_of_a_file_is_in_exactly_one_passage() {
    let text: String = (1..=200).map(|nth| format!("line {nth}\n")).collect();
    let cut = fragment::cut("a.rs", &text);
    let mut at = 1;
    for fragment in &cut {
        assert_eq!(fragment.from, at, "a line fell between two passages");
        at = fragment.to + 1;
    }
    assert_eq!(at - 1, 200);
}

#[test]
fn a_passage_reads_back_at_the_lines_it_claims() {
    let text: String = (1..=50).map(|nth| format!("line {nth}\n")).collect();
    assert_eq!(
        fragment::excerpt(&text, 10, 12),
        "line 10\nline 11\nline 12"
    );
    assert_eq!(fragment::excerpt(&text, 49, 80), "line 49\nline 50");
}

#[test]
fn a_name_that_runs_two_words_together_is_read_as_both() {
    let terms = scoring::terms("sessionExpiry in handle_timeout");
    assert!(terms.contains(&"session".to_owned()), "{terms:?}");
    assert!(terms.contains(&"expiry".to_owned()), "{terms:?}");
    assert!(terms.contains(&"timeout".to_owned()), "{terms:?}");
    assert!(
        !terms.contains(&"in".to_owned()),
        "a word in every file tells two passages apart: {terms:?}"
    );
}

#[test]
fn the_shortlist_prefers_a_file_named_after_the_question() {
    let fragments = vec![
        fragment("src/session.rs", 1, 3, "fn drop_old() { purge(); }"),
        fragment("src/unrelated.rs", 1, 3, "fn other() { session(); }"),
        fragment("src/a.rs", 1, 3, "fn nothing() {}"),
    ];
    let chosen = scoring::shortlist("session expiry", &fragments, 5, 4);
    assert_eq!(
        fragments[chosen[0]].path, "src/session.rs",
        "the path counts for more than a mention"
    );
    assert!(
        !chosen.iter().any(|nth| fragments[*nth].path == "src/a.rs"),
        "a passage sharing no word is not a candidate"
    );
}

#[test]
fn one_long_file_cannot_fill_the_shortlist() {
    let mut fragments: Vec<Fragment> = (0..20)
        .map(|nth| {
            fragment(
                "src/big.rs",
                nth * 10 + 1,
                nth * 10 + 9,
                "session expiry here",
            )
        })
        .collect();
    fragments.push(fragment("src/small.rs", 1, 3, "session expiry"));
    let chosen = scoring::shortlist("session expiry", &fragments, 10, 2);
    let from_big = chosen
        .iter()
        .filter(|nth| fragments[**nth].path == "src/big.rs")
        .count();
    assert_eq!(from_big, 2, "the cap per file did not hold");
    assert!(
        chosen
            .iter()
            .any(|nth| fragments[*nth].path == "src/small.rs"),
        "the file that would have been buried"
    );
}

#[test]
fn a_question_names_every_passage_by_where_it_is() {
    let held = [
        fragment("src/a.rs", 1, 9, "fn a() {}"),
        fragment("src/b.rs", 20, 30, "fn b() {}"),
    ];
    let shortlist: Vec<&Fragment> = held.iter().collect();
    let question = asking::question("what does a do", &shortlist);
    let input = question["input"].as_str().expect("an input");
    assert!(input.contains("src/a.rs:1-9"), "{input}");
    assert!(input.contains("src/b.rs:20-30"), "{input}");
    assert_eq!(question["role"], "decision");
    // Not the session's own model: one that writes scores badly and expensively, and on a
    // helper's budget spends the lot reasoning and answers nothing.
    assert_eq!(question["fallback"], "skip");
    assert_eq!(question["thinking"], "off");
}

#[test]
fn a_label_reads_back_as_a_place() {
    assert_eq!(
        asking::at("src/a.rs:120-158"),
        Some(("src/a.rs".to_owned(), 120, 158))
    );
    assert_eq!(
        asking::at("c:/win/a.rs:1-2"),
        Some(("c:/win/a.rs".to_owned(), 1, 2)),
        "a path may hold a colon of its own"
    );
    assert_eq!(asking::at("src/a.rs"), None);
    assert_eq!(asking::at("src/a.rs:0-5"), None);
    assert_eq!(asking::at("src/a.rs:9-2"), None);
}

#[test]
fn what_a_model_wrote_is_read_out_of_its_chatter() {
    let said = "Sure!\n```json\n{\"src/a.rs:1-9\": 3}\n```";
    let scores = asking::scores(said);
    assert_eq!(scores.len(), 1);
    assert_eq!(scores[0].path, "src/a.rs");
    assert_eq!(scores[0].from, 1);
    assert_eq!(scores[0].score, 10.0, "the top rung is the top score");
    assert!(asking::scores("no json at all").is_empty());
}

#[test]
fn a_mangled_label_is_dropped_rather_than_guessed_at() {
    let said = r#"{"src/a.rs": 3, "src/b.rs:1-4": 2}"#;
    let scores = asking::scores(said);
    assert_eq!(scores.len(), 1, "{scores:?}");
    assert_eq!(scores[0].path, "src/b.rs");
}

#[test]
fn a_score_outside_the_scale_is_brought_back_onto_it() {
    let said = r#"{"src/a.rs:1-4": 99}"#;
    assert_eq!(asking::scores(said)[0].score, 10.0);
}

#[test]
fn the_bookkeeping_a_decisions_reply_carries_is_not_read_as_a_passage() {
    // Its own reply names what it decided under `_decided`, which is not a label and not a score.
    let said = r#"{"src/a.rs:1-4": 3, "_decided": {"src/a.rs:1-4": {"p": 0.9}}}"#;
    let scores = asking::scores(said);
    assert_eq!(scores.len(), 1, "{scores:?}");
    assert_eq!(scores[0].path, "src/a.rs");
}

#[test]
fn a_rung_in_the_middle_lands_in_the_middle_of_the_scale() {
    // The model answers on the rungs' own scale and sese shows a score out of ten.
    let said = r#"{"src/a.rs:1-4": 0, "src/b.rs:1-4": 2}"#;
    let scores = asking::scores(said);
    let of = |path: &str| {
        scores
            .iter()
            .find(|s| s.path == path)
            .map(|s| s.score)
            .expect("scored")
    };
    assert_eq!(of("src/a.rs"), 0.0);
    assert!((of("src/b.rs") - 6.67).abs() < 0.01, "{:?}", of("src/b.rs"));
}

#[test]
fn a_fractional_rung_is_kept_rather_than_rounded_away() {
    // A model that decides answers with its confidence spread across the rungs, so 2.93 means
    // "almost certainly the top rung" and rounding it to 3 throws away the almost.
    let said = r#"{"src/a.rs:1-4": 2.93}"#;
    let score = asking::scores(said)[0].score;
    assert!(score > 9.5 && score < 10.0, "{score}");
}

#[test]
fn a_harness_with_no_model_says_so_rather_than_falling_silent() {
    let refused = asking::answered(r#"{"refused":"helper: this session has no model"}"#);
    let asking::Answer::Refused(because) = refused else {
        panic!("a refusal is an answer");
    };
    assert!(because.contains("no model"), "{because}");

    let told = asking::answered(r#"{"told":{"text":"{\"scores\":[]}","model":"m"}}"#);
    let asking::Answer::Said(said) = told else {
        panic!("a model answered");
    };
    assert_eq!(said, r#"{"scores":[]}"#);
}

#[test]
fn a_search_with_nothing_to_search_for_is_refused() {
    let sought = search(&Asked {
        query: "   ",
        root: ".",
        limit: 5,
        answered: None,
    });
    let Sought::Failed(why) = sought else {
        panic!("a blank question is not a search");
    };
    assert!(why.contains("a question"), "{why}");
}

#[test]
fn a_refused_question_still_answers_and_says_it_was_not_ranked() {
    let sought = search(&Asked {
        query: "session expiry",
        root: ".",
        limit: 5,
        answered: Some(r#"{"refused":"helper: no model is answering here"}"#),
    });
    let Sought::Found(found) = sought else {
        panic!("a refusal ends the search rather than failing it");
    };
    assert!(
        found.said.contains("not ranked by meaning"),
        "{}",
        found.said
    );
    assert!(
        found.said.contains("no model is answering"),
        "{}",
        found.said
    );
}

#[test]
fn a_passage_nothing_scored_well_is_not_shown() {
    let sought = search(&Asked {
        query: "session expiry",
        root: ".",
        limit: 5,
        answered: Some(
            r#"{"told":{"text":"{\"scores\":[{\"at\":\"src/lib.rs:1-4\",\"score\":1}]}"}}"#,
        ),
    });
    let Sought::Found(found) = sought else {
        panic!("still a result");
    };
    assert!(found.said.contains("not ranked"), "{}", found.said);
}

#[test]
fn candidates_are_read_in_groups_a_single_read_can_carry() {
    let many: Vec<(String, u64)> = (0..150)
        .map(|nth| (format!("src/f{nth}.rs"), 4_000))
        .collect();
    let groups = grouped(&many);
    assert!(groups.len() > 1);
    assert!(groups.iter().all(|group| group.len() <= PER_READ));
    assert_eq!(
        groups.iter().map(Vec::len).sum::<usize>(),
        150,
        "a candidate fell out between groups"
    );
}

#[test]
fn one_file_bigger_than_a_whole_group_is_still_read() {
    let groups = grouped(&[("src/one.rs".to_owned(), BYTES_PER_READ * 2)]);
    assert_eq!(groups, vec![vec!["src/one.rs".to_owned()]]);
}
